# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
name: days-on-github

services:
  server:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 3000:3000
    cap_add:
      - SYS_ADMIN
    container_name: days-on-github-server
    volumes:
      - ./logs/server:/var/log/server
  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: names-on-github-nginx
    restart: unless-stopped
    environment:
      - STAGING=1
      - DEBUG=1
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes: # Storage can be either a
      - ./logs/ngnix:/var/log/nginx
      - nginx_secrets:/etc/letsencrypt # Docker managed volume (see list at the bottom)
      - ./user_conf.d:/etc/nginx/user_conf.d # or a host mount with a relative or full path.

volumes:
  nginx_secrets:
# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker-compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

