name: build-and-push-docker-image

on:
  push:
  pull_request:
    types: [opened, reopened]

env:
  TEST_TAG: user/app:test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: pikilee/days-on-github

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test
        run: |
          docker run --rm -d --cap-add=SYS_ADMIN -p 3000:3000 --env NITRO_GITHUB_CLIENT_TOKEN=${{secrets.NITRO_GITHUB_CLIENT_TOKEN}} ${{ env.TEST_TAG }}

      - name: Wait for response
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: 'http://localhost:3000/username/PikiLee'
          responseCode: '200'
          timeout: 2000
          interval: 500

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
