name: ci

on:
  push:

env:
  TEST_TAG: pikilee/days-on-github:test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: pikilee/days-on-github

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Test
        run: |
          export NITRO_GITHUB_CLIENT_TOKEN=${{ secrets.NITRO_GITHUB_CLIENT_TOKEN }}
          docker run --rm ${{ env.TEST_TAG }} -d
          curl 'http://localhost:3000/username/pikilee'

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
